import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { FirebaseProvider } from "./context/firebase";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GDSC SOU",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative dark:bg-black`}>
        <FirebaseProvider>
          <Navbar />
          {children}
          <Footer />
        </FirebaseProvider>
      </body>
    </html>
  );
}
